name: .NET Core

on: [push, pull_request]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Restore dotnet tools
      run: dotnet tool restore
    - name: Prepare sonarqube
      run: dotnet sonarscanner begin -d:sonar.host.url=https://sonarcloud.io -organization:dnperfors-github -key:dnperfors_TestableHttpClient -version:`dotnet gitversion -showvariable semver` -d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml -d:sonar.login=${{secrets.SONARCLOUD_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build source code
      run: dotnet build --configuration Release --no-restore
    - name: Test with dotnet
      run: dotnet test --configuration Release --no-build --collect="Code Coverage" --framework="netcoreapp3.1"
    - name: Upload sonarqube results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet sonarscanner end -d:sonar.login=${{secrets.SONARCLOUD_TOKEN}}
    - name: Check source file format
      run: dotnet format --check
    - name: Pack
      run: dotnet pack --output ./artifacts --configuration Release --no-build
    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: ./artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./**/TestResults/**/coverage.opencover.xml

  testFrameworkVersions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1'
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build source code
      run: dotnet build --configuration Release --no-restore
    - name: Test with dotnet
      run: dotnet test --configuration Release --no-build

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - uses: actions/download-artifact@v2
      with:
        name: artifacts
        path: ./artifacts
    - name: Publish packages
      run: dotnet nuget push './artifacts/**/*.nupkg' --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_TOKEN}}
